# ============================================== #
# PATHS
# ============================================== #
paths:
  data:
    handling: ../Data/Handling/
    output: ../Data/Output/
  figures: ../Figures/

# ============================================== #
# PARAMS
# ============================================== #
params:
  emissionvar: Emissions|CO2|Energy and Industrial Processes
  percred: 0.66
  curpol_scenario: ELV-SSP2-CP-D0

# ============================================== #
# DATABASE
# ============================================== #
database:
  ecemf:
    name: ecemf_internal
  elevate:
    name: elevate_internal
  committed:
    name: committed_internal

# ============================================== #
# INDICATORS, NAMES AND EXPLANATIONS
# ============================================== #

indicators_to_exclude:
  - R2_time
  - R4_sensprim
  - R5_sensdem
  - C1_cost

indicators:
  R1_rai:
    name: Relative abatement index
    explanation: Relative change of CO<sub>2</sub> emissions (from energy and industrial processes) compared to 2020 values. Positive means that CO<sub>2</sub> is reducing.
    plottype: line
    axisnorm: n
    horline: y
  R2_time:
    name: Time scale of carbon price response
    explanation: Number of years before 66% reduction in CO<sub>2</sub> emissions between 2020 and 2050
    plottype: bar
    axisnorm: n
    horline: n
  R3_speedmax:
    name: Maximum mitigation speed
    explanation: Maximum of CO<sub>2</sub> emission reductions in 5-year increments between 2020 and 2050
    plottype: bar
    axisnorm: n
    horline: n
  R4_sensprim:
    name: Sensitivity primary energy mix
    explanation: Average (normalized) scenario variance in all primary energy carriers
    plottype: line
    axisnorm: y
    horline: n
  R5_sensdem:
    name: Sensitivity final energy consumption in demand sectors
    explanation: Average (normalized) scenario variance in final energy demand across end-use sectors
    plottype: line
    axisnorm: y
    horline: n
  M1_cir:
    name: Carbon intensity reduction
    explanation: Reduction in carbon intensity (i.e., CO<sub>2</sub> emissions per unit of final energy demand)
    plottype: line
    axisnorm: y
    horline: y
  M2_eir:
    name: Energy intensity reduction
    explanation: Reduction in energy intensity (i.e., final energy demand per unit of GDP)
    plottype: line
    axisnorm: y
    horline: y
  M3_cc:
    name: Carbon capture
    explanation: CO<sub>2</sub> emissions captured, including DAC, BECCS and fossil fuel use with carbon capture
    plottype: line
    axisnorm: n
    horline: n
  M4_nonco2:
    name: Role of non-CO<sub>2</sub> abatement
    explanation: Non-CO<sub>2</sub> emissions reduction (2020 value minus 2050 value) divided by CO<sub>2</sub> emission reduction (2020 value minus 2050 value). All emissions are looked at here (also from land use). Positive values are expected if both non-CO2 and CO2 reduce. Higher values indicate a larger role of non-CO2 abatement. Negative values indicate non-CO2 increase rather than decrease (for interpretation purposes, potential but rare CO2 increases are omitted from this indicator).
    plottype: bar
    axisnorm: y
    horline: y
  ES1_coal:
    name: Coal share in energy mix
    explanation: Share of coal in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES2_oil:
    name: Oil share in energy mix
    explanation: Share of oil in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES3_gas:
    name: Gas share in energy mix
    explanation: Share of gas in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES4_solar:
    name: Solar share in energy mix
    explanation: Share of solar energy in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES5_wind:
    name: Wind share in energy mix
    explanation: Share of wind energy in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES6_biomass:
    name: Biomass share in energy mix
    explanation: Share of biomass energy in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ES7_nuclear:
    name: Nuclear share in energy mix
    explanation: Share of nuclear energy in primary energy supply
    plottype: line
    axisnorm: y
    horline: n
  ED1_etrans:
    name: Electrification of transport
    explanation: Share of electricity in final energy demand for transport
    plottype: line
    axisnorm: y
    horline: n
  ED2_eindus:
    name: Electrification of industry
    explanation: Share of electricity in final energy demand for industry
    plottype: line
    axisnorm: y
    horline: n
  ED3_ebuild:
    name: Electrification of buildings
    explanation: Share of electricity in final energy demand in the residential and commercial sector
    plottype: line
    axisnorm: y
    horline: n
  ED4_emise:
    name: Net electricity emissions
    explanation: Net emissions from electricity generation, accounting for CCS
    plottype: line
    axisnorm: n
    horline: n
  ED5_hydrogen:
    name: Hydrogen use
    explanation: Share of hydrogen in final energy use
    plottype: line
    axisnorm: y
    horline: n
  C1_cost:
    name: Cumulative costs per abatement value
    explanation: Cumulative additional costs divided by the cumulative sum of carbon prices times the marginal CO<sub>2</sub> emission reductions (over period 2020-2050)
    plottype: bar
    axisnorm: y
    horline: n
  C2_ti:
    name: Transformation index
    explanation: Sum of absolute changes in primary energy carrier fraction between 2020 and 2050
    plottype: bar
    axisnorm: y
    horline: n
  C3_dem:
    name: Demand shifts
    explanation: Sum of absolute changes in final energy demand in end-use sectors between 2020 and 2050
    plottype: bar
    axisnorm: y
    horline: n

# ============================================== #
# LISTS OF SCENARIOS, REGIONS, MODELS AND VARIABLES
# ============================================== #
scenarios:
  - ELV-SSP2-CP-D0
  - ELV-SSP2-NDC-D0
  - ELV-SSP2-1150

regions:
  - World
  - China
  - India
  - Indonesia
  - Saudi-Arabia
  - Viet Nam
  - Pakistan
  - Brazil
  - Poland
  - Europe

regional_mapping:
  World:
    - World
  China:
    - IMAGE 3.3|China
    - GCAM-CGS-ELEVATE|China
    - MESSAGEix-GLOBIOM 2.0|China
    - WITCH 5.0|China
    - REMIND 3.3|China and Taiwan
    - AIM/Hub-Global 2.4|China
    - CHA
  India:
    - IMAGE 3.3|India
    - GCAM-CGS-ELEVATE|India
    - MESSAGEix-GLOBIOM 2.0|South Asia
    - WITCH 5.0|India
    - REMIND 3.3|India
    - AIM/Hub-Global 2.4|India
    - IND
  Indonesia:
    - IMAGE 3.3|Indonesia
    - GCAM-CGS-ELEVATE|Indonesia
    - MESSAGEix-GLOBIOM 2.0|Other Pacific Asia
    - WITCH 5.0|Indonesia
    - REMIND 3.3|Other Asia
    - AIM/Hub-Global 2.4|Rest of East and South East Asia
    - OAS
  Saudi-Arabia:
    - IMAGE 3.3|Middle East
    - GCAM-CGS-ELEVATE|Middle East
    - MESSAGEix-GLOBIOM 2.0|Middle East and North Africa
    - WITCH 5.0|Middle East and North Africa
    - REMIND 3.3|Middle East and North Africa
    - AIM/Hub-Global 2.4|Middle East
    - MEA
  Viet Nam:
    - IMAGE 3.3|South-East Asia
    - GCAM-CGS-ELEVATE|Southeast Asia
    - MESSAGEix-GLOBIOM 2.0|Rest of Centrally Planned Asia
    - WITCH 5.0|South East Asia
    - REMIND 3.3|Other Asia
    - AIM/Hub-Global 2.4|Rest of East and South East Asia
    - OAS
  Pakistan:
    - IMAGE 3.3|Other Southern Asia
    - GCAM-CGS-ELEVATE|Pakistan
    - MESSAGEix-GLOBIOM 2.0|South Asia
    - WITCH 5.0|South Asia
    - REMIND 3.3|Other Asia
    - AIM/Hub-Global 2.4|Rest of Asia
    - OAS
  Brazil:
    - IMAGE 3.3|Brazil
    - GCAM-CGS-ELEVATE|Brazil
    - MESSAGEix-GLOBIOM 2.0|Latin America and the Caribbean
    - WITCH 5.0|Brazil
    - REMIND 3.3|Latin America and the Caribbean
    - AIM/Hub-Global 2.4|Brazil
    - LAM
  Poland:
    - IMAGE 3.3|Central Europe
    - GCAM-CGS-ELEVATE|EU-12
    - MESSAGEix-GLOBIOM 2.0|Eastern Europe
    - WITCH 5.0|Europe (EU+EFTA+Balkan Countries and Turkey)
    - REMIND 3.3|EU 28
    - AIM/Hub-Global 2.4|EU
    - EUR
  Europe:
    - Europe (R10)
    - EUR

models:
  - AIM/Hub-Global 2.4
  - GCAM-CGS-ELEVATE
  - IMAGE 3.3
  - MESSAGEix-GLOBIOM 2.0
  - REMIND 3.3
  - WITCH 5.0

required_variables:
  - Emissions|CO2|Energy and Industrial Processes
  - GDP|PPP
  - Primary Energy
  - Primary Energy|Solar
  - Primary Energy|Wind
  - Primary Energy|Coal
  - Primary Energy|Oil
  - Primary Energy|Gas
  - Primary Energy|Nuclear
  - Primary Energy|Biomass
  - Final Energy
  - Final Energy|Industry
  - Final Energy|Transportation
  - Final Energy|Residential and Commercial
  - Carbon Capture
  - Emissions|Kyoto Gases
  - Emissions|CO2
  - Final Energy|Transportation|Electricity
  - Final Energy|Industry|Electricity
  - Final Energy|Residential and Commercial|Electricity
  - Emissions|CO2|Energy|Supply|Electricity
  - Final Energy|Hydrogen
  - Policy Cost|Consumption Loss
  - Policy Cost|Area under MAC Curve
  - Policy Cost|Additional Total Energy System Cost
  - Price|Carbon
