# ============================================== #
# PATHS
# ============================================== #
paths:
  data:
    handling: ../Data/Handling/
    output: ../Data/Output/
  figures: ../Figures/

# ============================================== #
# DATABASE
# ============================================== #
database:
  ecemf:
    name: ecemf_internal
  elevate:
    name: elevate_internal
  committed:
    name: committed_internal
  username: none
  password: none

# ============================================== #
# PARAMS
# ============================================== #
params:
  emissionvar: Emissions|CO2|Energy and Industrial Processes
  percred: 0.66
  curpol_scenario: ELV-SSP2-CP-D0

# ============================================== #
# LISTS OF SCENARIOS, REGIONS, MODELS AND VARIABLES
# ============================================== #
scenarios:
  - ELV-SSP2-CP-D0
  - ELV-SSP2-NDC-D0
  - ELV-SSP2-1150

regions:
  - World
  - China
  - India
  - Indonesia
  - Europe

regional_mapping:
  World:
    - World
  China:
    - IMAGE 3.3|China
    - GCAM-CGS-ELEVATE|China
    - MESSAGEix-GLOBIOM 2.0|China
    - WITCH 5.0|China
    - REMIND 3.3|China and Taiwan
    - AIM/Hub-Global 2.4|China
  India:
    - IMAGE 3.3|India
    - GCAM-CGS-ELEVATE|India
    - MESSAGEix-GLOBIOM 2.0|South Asia
    - WITCH 5.0|India
    - REMIND 3.3|India
    - AIM/Hub-Global 2.4|India
  Indonesia:
    - IMAGE 3.3|Indonesia
    - GCAM-CGS-ELEVATE|Indonesia
    - MESSAGEix-GLOBIOM 2.0|Other Pacific Asia
    - WITCH 5.0|Indonesia
  Europe:
    - Europe (R10)

models:
  - AIM/Hub-Global 2.4
  - GCAM-CGS-ELEVATE
  - IMAGE 3.3
  - MESSAGEix-GLOBIOM 2.0
  - REMIND 3.3
  - WITCH 5.0

required_variables:
  - Emissions|CO2|Energy and Industrial Processes
  - GDP|PPP
  - Primary Energy
  - Primary Energy|Solar
  - Primary Energy|Wind
  - Primary Energy|Coal
  - Primary Energy|Oil
  - Primary Energy|Gas
  - Primary Energy|Nuclear
  - Primary Energy|Biomass
  - Final Energy
  - Final Energy|Industry
  - Final Energy|Transportation
  - Final Energy|Residential and Commercial
  - Carbon Capture
  - Emissions|Kyoto Gases
  - Emissions|CO2
  - Final Energy|Transportation|Electricity
  - Final Energy|Industry|Electricity
  - Final Energy|Residential and Commercial|Electricity
  - Emissions|CO2|Energy|Supply|Electricity
  - Final Energy|Hydrogen
  - Policy Cost|Consumption Loss
  - Policy Cost|Area under MAC Curve
  - Policy Cost|Additional Total Energy System Cost
  - Price|Carbon
